### ISSUE TITLE
Version Conflict Error

### ISSUE THREAD

**Issue by srk2014** [argosopentech/LibreTranslate-init#1]
Thanks for offering this tool. I am trying to set this one on Ubuntu, and followed the instructions as outlined. However, I am seeing the following "VersionConflict" error. Any suggestion to address this issue? After following these steps, how can I map the libretranslate server to a domain of interest?

Cloning into '/home/libretranslate/LibreTranslate'...
remote: Enumerating objects: 833, done.
remote: Counting objects: 100% (169/169), done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 833 (delta 103), reused 84 (delta 73), pack-reused 664
Receiving objects: 100% (833/833), 495.42 KiB | 3.93 MiB/s, done.
Resolving deltas: 100% (462/462), done.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (virtualenv 20.0.17 (/usr/lib/python3/dist-packages), Requirement.parse('virtualenv==16.7.8'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'virtualenv==16.7.8' distribution was not found and is required by the application
/home/libretranslate/LibreTranslate-init/setup.sh: 22: /home/libretranslate/LibreTranslate/env/bin/pip: not found
/home/libretranslate/LibreTranslate-init/setup.sh: 25: /home/libretranslate/LibreTranslate/env/bin/pip: not found
/home/libretranslate/LibreTranslate-init/setup.sh: 26: /home/libretranslate/LibreTranslate/env/bin/libretranslate: not found

**Comment by PJ-Finlay** [comment]
It looks like it's having issues installing virtualenv.

Does this work:
```
sudo apt-get install python3-virtualenv

```

**Comment by srk2014** [comment]
"python3-virtualenv is already the newest version (20.0.17-1ubuntu0.4)."

I have the latest virtual env version, whereas the one used for the translator is "virtualenv==16.7.8", which is causing a mismatch.

**Comment by PJ-Finlay** [comment]
Where are you seeing `"virtualenv==16.7.8"`? The script should just try to install and the latest version of virtualenv from the package manager.

**Comment by PJ-Finlay** [comment]
Are you able to make a virtual environment? Ex:
```
virtualenv env

```

**Comment by srk2014** [comment]
I followed the steps as outlined. I believe that the virtual env is set in
the shell script. I ran the shell script and when it reaches this point, it
is throwing an error message, that I already shared with you.

**Comment by srk2014** [comment]
Right when this code is executed,
# Download dependencies and run LibreTranslate on port 5000
~/LibreTranslate-init/setup.sh

**Comment by srk2014** [comment]
If I just run virtual env step, I am seeing the same error as I got before -

$ virtualenv ~/LibreTranslate/env
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (virtualenv 20.0.17 (/usr/lib/python3/dist-packages), Requirement.parse('virtualenv==16.7.8'))
