### ISSUE TITLE
error with beautifulsoup4==4.9.3

### ISSUE THREAD

**Issue by Collide** [argosopentech/LibreTranslate-init#12]
Hello everyone, I have tried to install with freetranslate-init following all instructions; but fails in the installation when trying to use the beautifulsoup4===4.9.3 library. the system tells me that I have the beautifulsoup4 4.11.1. so unlock it and install the specific version (4.9.3) but it still doesn't work and show me errors.

What can I do?

```
Successfully built expiringdict flask-swagger-ui flask-swagger polyglot pycld2 pyicu
__ERROR: translatehtml 1.5.2 has requirement beautifulsoup4==4.9.3, but you'll have beautifulsoup4 4.11.1 which is incompatible.__
Installing collected packages: backports.zoneinfo, tzdata, pytz-deprecation-shim, tzlocal, pytz, six, APScheduler, wrapt, deprecated, typing-extensions, pyparsing, packaging, limits, click, MarkupSafe, Jinja2, Werkzeug, zipp, importlib-metadata, itsdangerous, Flask, pygments, commonmark, rich, Flask-Limiter, appdirs, soupsieve, beautifulsoup4, lxml, certifi, charset-normalizer, urllib3, idna, requests, numpy, tqdm, torch, protobuf, stanza, PyYAML, ctranslate2, sentencepiece, argostranslate, translatehtml, argos-translate-files, expiringdict, flask-swagger-ui, flask-swagger, morfessor, polyglot, pycld2, pyicu, waitress, libretranslate
  Running setup.py develop for libretranslate
Successfully installed APScheduler-3.9.1 Flask-2.1.2 Flask-Limiter-2.4.5.1 Jinja2-3.1.2 MarkupSafe-2.1.1 PyYAML-6.0 Werkzeug-2.1.2 appdirs-1.4.4 argos-translate-files-1.1.0 argostranslate-1.7.0 backports.zoneinfo-0.2.1 beautifulsoup4-4.11.1 certifi-2022.6.15 charset-normalizer-2.0.12 click-8.1.3 commonmark-0.9.1 ctranslate2-2.17.0 deprecated-1.2.13 expiringdict-1.2.1 flask-swagger-0.2.14 flask-swagger-ui-3.36.0 idna-3.3 importlib-metadata-4.12.0 itsdangerous-2.1.2 libretranslate limits-2.7.0 lxml-4.8.0 morfessor-2.0.6 numpy-1.23.1 packaging-21.3 polyglot-16.7.4 protobuf-4.21.4 pycld2-0.41 pygments-2.12.0 pyicu-2.9 pyparsing-3.0.9 pytz-2022.1 pytz-deprecation-shim-0.1.0.post0 requests-2.28.0 rich-12.5.1 sentencepiece-0.1.96 six-1.16.0 soupsieve-2.3.2.post1 stanza-1.1.1 torch-1.12.0 tqdm-4.64.0 translatehtml-1.5.2 typing-extensions-4.3.0 tzdata-2022.1 tzlocal-4.2 urllib3-1.26.11 waitress-2.1.2 wrapt-1.14.1 zipp-3.8.1
Traceback (most recent call last):
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (beautifulsoup4 4.11.1 (/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages), Requirement.parse('beautifulsoup4==4.9.3'), {'translatehtml'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/libretranslate/LibreTranslate/env/bin/libretranslate", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
__pkg_resources.DistributionNotFound: The 'beautifulsoup4==4.9.3' distribution was not found and is required by translatehtml__
```

**Comment by w1n5l0w** [comment]
You can unistall the current version of beautifulsoup4 and install the required version:
```
pip uninstall beautifulsoup4
pip install beautifulsoup4==4.9.3
```
