### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by dukei** [argosopentech/LibreTranslate-init#14]
`~/LibreTranslate-init/setup.sh` results in error
```
ERROR: translatehtml 1.5.2 has requirement beautifulsoup4==4.9.3, but you'll have beautifulsoup4 4.11.1 which is incompatible.
Installing collected packages: pytz, six, backports.zoneinfo, tzdata, pytz-deprecation-shim, tzlocal, APScheduler, typing-extensions, pygments, commonmark, rich, wrapt, deprecated, pyparsing, packaging, limits, MarkupSafe, Werkzeug, zipp, importlib-metadata, Jinja2, itsdangerous, click, Flask, Flask-Limiter, appdirs, nvidia-cublas-cu11, nvidia-cudnn-cu11, nvidia-cuda-runtime-cu11, nvidia-cuda-nvrtc-cu11, torch, numpy, protobuf, idna, certifi, charset-normalizer, urllib3, requests, tqdm, stanza, PyYAML, ctranslate2, sentencepiece, argostranslate, soupsieve, beautifulsoup4, translatehtml, lxml, argos-translate-files, expiringdict, flask-swagger-ui, flask-swagger, morfessor, polyglot, pycld2, pyicu, async-timeout, redis, waitress, libretranslate
  Running setup.py develop for libretranslate
Successfully installed APScheduler-3.9.1 Flask-2.2.2 Flask-Limiter-2.6.3 Jinja2-3.1.2 MarkupSafe-2.1.1 PyYAML-6.0 Werkzeug-2.2.2 appdirs-1.4.4 argos-translate-files-1.1.0 argostranslate-1.7.0 async-timeout-4.0.2 backports.zoneinfo-0.2.1 beautifulsoup4-4.11.1 certifi-2022.9.24 charset-normalizer-2.1.1 click-8.1.3 commonmark-0.9.1 ctranslate2-2.17.0 deprecated-1.2.13 expiringdict-1.2.2 flask-swagger-0.2.14 flask-swagger-ui-4.11.1 idna-3.4 importlib-metadata-5.0.0 itsdangerous-2.1.2 libretranslate limits-2.7.1 lxml-4.8.0 morfessor-2.0.6 numpy-1.23.4 nvidia-cublas-cu11-11.10.3.66 nvidia-cuda-nvrtc-cu11-11.7.99 nvidia-cuda-runtime-cu11-11.7.99 nvidia-cudnn-cu11-8.5.0.96 packaging-21.3 polyglot-16.7.4 protobuf-4.21.9 pycld2-0.41 pygments-2.13.0 pyicu-2.10.2 pyparsing-3.0.9 pytz-2022.6 pytz-deprecation-shim-0.1.0.post0 redis-4.3.4 requests-2.28.1 rich-12.6.0 sentencepiece-0.1.96 six-1.16.0 soupsieve-2.3.2.post1 stanza-1.1.1 torch-1.13.0 tqdm-4.64.1 translatehtml-1.5.2 typing-extensions-4.4.0 tzdata-2022.6 tzlocal-4.2 urllib3-1.26.12 waitress-2.1.2 wrapt-1.14.1 zipp-3.10.0
Traceback (most recent call last):
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (beautifulsoup4 4.11.1 (/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages), Requirement.parse('beautifulsoup4==4.9.3'), {'translatehtml'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/libretranslate/LibreTranslate/env/bin/libretranslate", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'beautifulsoup4==4.9.3' distribution was not found and is required by translatehtml
$
```
second attempt results in 
```
Installing collected packages: libretranslate
  Attempting uninstall: libretranslate
    Found existing installation: libretranslate 1.3.1
    Uninstalling libretranslate-1.3.1:
      Successfully uninstalled libretranslate-1.3.1
  Running setup.py develop for libretranslate
Successfully installed libretranslate
Traceback (most recent call last):
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (beautifulsoup4 4.11.1 (/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages), Requirement.parse('beautifulsoup4==4.9.3'), {'translatehtml'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/libretranslate/LibreTranslate/env/bin/libretranslate", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/libretranslate/LibreTranslate/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'beautifulsoup4==4.9.3' distribution was not found and is required by translatehtml
$
```

**Comment by PJ-Finlay** [comment]
Do you already have `beautifulsoup4` installed on your system? You can try uninstalling it or using a virtual environment.

**Comment by dukei** [comment]
well, I uninstalled it globally but it did not help. I activated LibreTranslate virtualenv with `source ~/LibreTranslate/env/bin/activate`, uninstalled beautifulsoup4, but it didn't help again. LibreTranslate installed bs4 with the following log:
```
Collecting beautifulsoup4>=4.9.3
  Downloading beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
     |████████████████████████████████| 128 kB 1.1 MB/s
```

I uninstalled it in virtualenv again and installed 4.9.3 manually. It helped, thank you. But now I had the following errors:
```
Installing transliteration models for the following languages: ar, az, zh, cs, da, nl, eo, fi, fr, de, el, he, hi, hu, id, ga, it
[polyglot_data] Error loading transliteration2.ar: HTTP Error 404: Not
[polyglot_data]     Found
[polyglot_data] Error loading transliteration2.az: HTTP Error 404: Not
[polyglot_data]     Found
[polyglot_data] Error loading transliteration2.zh: HTTP Error 404: Not
[polyglot_data]     Found
[polyglot_data] Error loading transliteration2.cs: HTTP Error 404: Not
[polyglot_data]     Found
[polyglot_data] Error loading transliteration2.da: HTTP Error 404: Not
[polyglot_data]     Found
[polyglot_data] Error loading transliteration2.nl: HTTP Error 404: Not
[polyglot_data]     Found
[polyglot_data] Error loading transliteration2.eo: HTTP Error 404: Not
[polyglot_data]     Found
[polyglot_data] Error loading transliteration2.fi: HTTP Error 404: Not
[polyglot_data]     Found
[polyglot_data] Error loading transliteration2.fr: HTTP Error 404: Not
[polyglot_data]     Found
[polyglot_data] Error loading transliteration2.de: HTTP Error 404: Not
[polyglot_data]     Found
[polyglot_data] Error loading transliteration2.el: HTTP Error 404: Not
[polyglot_data]     Found
[polyglot_data] Error loading transliteration2.he: HTTP Error 404: Not
[polyglot_data]     Found
[polyglot_data] Error loading transliteration2.hi: HTTP Error 404: Not
[polyglot_data]     Found
[polyglot_data] Error loading transliteration2.hu: HTTP Error 404: Not
[polyglot_data]     Found
[polyglot_data] Error loading transliteration2.id: HTTP Error 404: Not
[polyglot_data]     Found
[polyglot_data] Error loading transliteration2.ga: HTTP Error 404: Not
[polyglot_data]     Found
[polyglot_data] Error loading transliteration2.it: HTTP Error 404: Not
[polyglot_data]     Found
Running on http://127.0.0.1:5000

```

Is it normal behaviour?

**Comment by dukei** [comment]
It is not a problem of install script. It is LibreTranslate issue.

**Comment by argosopentech** [comment]
This was the Polyglot issue, it should be fixed now:
https://github.com/LibreTranslate/LibreTranslate/issues/344
