### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'db'

### ISSUE THREAD

**Issue by argosopentech** [argosopentech/LibreTranslate-init#18]
I sometimes see this error but it doesn't seem to cause issues.

```
Traceback (most recent call last):
  File "/home/libretranslate/LibreTranslate/env/bin/libretranslate", line 8, in <module>
    sys.exit(main())
  File "/home/libretranslate/LibreTranslate/env/lib/python3.10/site-packages/libretranslate/main.py", line 192, in main
    app = create_app(args)
  File "/home/libretranslate/LibreTranslate/env/lib/python3.10/site-packages/libretranslate/app.py", line 1069, in create_app
    Session(app)
  File "/home/libretranslate/LibreTranslate/env/lib/python3.10/site-packages/flask_session/__init__.py", line 54, in __init__
    self.init_app(app)
  File "/home/libretranslate/LibreTranslate/env/lib/python3.10/site-packages/flask_session/__init__.py", line 61, in init_app
    app.session_interface = self._get_interface(app)
  File "/home/libretranslate/LibreTranslate/env/lib/python3.10/site-packages/flask_session/__init__.py", line 90, in _get_interface
    session_interface = FileSystemSessionInterface(
  File "/home/libretranslate/LibreTranslate/env/lib/python3.10/site-packages/flask_session/sessions.py", line 322, in __init__
    self.cache = FileSystemCache(cache_dir, threshold=threshold, mode=mode)
  File "/home/libretranslate/LibreTranslate/env/lib/python3.10/site-packages/cachelib/file.py", line 65, in __init__
    os.makedirs(self._path)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'db'
```

**Comment by manuelkamp** [comment]
I get the same error when trying to install a newer version

**Comment by danielmnb1** [comment]
does not work with this user 

only skip the part of adding the user

and in the libretranslate.service file

user and group = root

and in nginx = the ip of the server 

and it should work

**Comment by danielmnb1** [comment]
solution 2 

create dir in /home/libretranslate/db

ready

**Comment by manuelkamp** [comment]
No, this does not solve it. I created directory /home/libretranslate/db (but there is one in /home/libretranslate/LibreTranslate/db already, where it should be).

I cannot skip part of adding user, because it is installed in python venv and not in root.

**Comment by manuelkamp** [comment]
OK, this is how i got the update working (note that it is now running under root venv and not libretranslate user anymore):

`su libretranslate`
`sudo systemctl stop libretranslate`
`cp /root/libretranslate/LibreTranslate/libretranslate/templates/index.html /tmp/index.html`
`rm -rf ~/LibreTranslate`
`exit`
`git clone https://github.com/LibreTranslate/LibreTranslate.git ~/LibreTranslate`
`virtualenv ~/LibreTranslate/env`
`~/LibreTranslate/env/bin/pip install gunicorn`
`~/LibreTranslate/env/bin/pip install ~/LibreTranslate/ --no-cache-dir`
`~/LibreTranslate/env/bin/pip uninstall beautifulsoup4`
`~/LibreTranslate/env/bin/pip install beautifulsoup4==4.9.3`
`~/LibreTranslate/env/bin/libretranslate`
`nano /etc/systemd/system/libretranslate.service`
edit and change user/path from /home/libretranslate to /root (don't forget to adapt to your url!):
```
[Unit]
Description=LibreTranslate WSGI with Gunicorn and Nginx
After=network.target

[Service]
User=root
Group=www-data
WorkingDirectory=/root/LibreTranslate
Environment="PATH=/root/LibreTranslate/env/bin"
ExecStart=/root/LibreTranslate/env/bin/gunicorn --workers 3 --bind unix:libretranslate.sock -m 007 wsgi:app(api_keys=True, req_limit="5", batch_limit="2", get_api_key_link="https://translate.somedomain.com/get-api-key")
Restart=always
ExecReload=/bin/kill -s HUP $MAINPID
KillMode=mixed
TimeoutStopSec=1

[Install]
WantedBy=multi-user.target
```
`cp /tmp/index.html /root/LibreTranslate/libretranslate/templates/index.html`
`systemctl start libretranslate`
`systemctl enable libretranslate`
`nano /etc/nginx/sites-available/default`
Also change home to root here (don't forget to adapt to your url!):
```
server {
    listen 80;
    server_name localhost translate.someserver.com;

    location / {
        include proxy_params;
        proxy_pass http://unix:/root/LibreTranslate/libretranslate.sock;
    }
}
```
`nginx -t`
`systemctl restart nginx`

for future updates just skip the first line (and later the "exit" command).

**Comment by falves1** [comment]
I am affected also, on a blank  computer. Can somebody update the instructions?

**Comment by maxlinux2000** [comment]
please add this to /etc/sudoers.d/libretranslate 

`libretranslate ALL=NOPASSWD: /usr/local/bin/libretranslate`

here my systemd service 
```

root@debian:/etc/systemd/system# cat libretranslate.service 
[Unit]
Description=LibreTranslate
After=network.target
[Service]
User=libretranslate
Group=libretranslate
WorkingDirectory=/opt/libretranslate/
ExecStart=sudo  -u libretranslate /usr/local/bin/libretranslate --host 127.0.0.1 --port 5000
#--disable-files-translation
Restart=always
#CPUQuota=50%

[Install]
WantedBy=multi-user.target

```

**Comment by sunra** [comment]
Debian 12. 

Loaded support for 44 languages (88 models total)!
Traceback (most recent call last):
  File "/home/libretranslate/LibreTranslate/env/bin/libretranslate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/libretranslate/LibreTranslate/env/lib/python3.11/site-packages/libretranslate/main.py", line 226, in main
    app = create_app(args)
          ^^^^^^^^^^^^^^^^
  File "/home/libretranslate/LibreTranslate/env/lib/python3.11/site-packages/libretranslate/app.py", line 1130, in create_app
    Session(app)
  File "/home/libretranslate/LibreTranslate/env/lib/python3.11/site-packages/flask_session/__init__.py", line 54, in __init__
    self.init_app(app)
  File "/home/libretranslate/LibreTranslate/env/lib/python3.11/site-packages/flask_session/__init__.py", line 61, in init_app
    app.session_interface = self._get_interface(app)
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/libretranslate/LibreTranslate/env/lib/python3.11/site-packages/flask_session/__init__.py", line 90, in _get_interface
    session_interface = FileSystemSessionInterface(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/libretranslate/LibreTranslate/env/lib/python3.11/site-packages/flask_session/sessions.py", line 322, in __init__
    self.cache = FileSystemCache(cache_dir, threshold=threshold, mode=mode)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/libretranslate/LibreTranslate/env/lib/python3.11/site-packages/cachelib/file.py", line 80, in __init__
    os.makedirs(self._path)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: 'db'

**Comment by Darecjo** [comment]
> `libretranslate ALL=NOPASSWD: /usr/local/bin/libretranslate`

How did you get the .env settings to work ?

**Comment by lotigara** [comment]
I've solved this issue by changing working dir from `root`'s working dir to `libretranslate`'s one. But there is another way to solve this issue: invoke `su` with `-l` option, this can be added to the `README.md`.
